# Workflow to deploy on ECS

name: Deploy to Amazon ECS

on:
  push:
    branches:
      - main
      - develop
      - test
      - release
    tags:
      - "*"
    pull_request:
      branches:
        - develop


env:
  AWS_REGION: "us-east-2"                   # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: "kubelancer-dev-registry"           # set this to your Amazon ECR repository name
  ECS_SERVICE: "kubelancer-dev-service"                # set this to your Amazon ECS service name
  ECS_CLUSTER: "kubelancer-dev-cluster"                 # set this to your Amazon ECS cluster name
  ECS_TASK_DEFINITION: ".aws/task-definition.json"  # set this to the path to your Amazon ECS task definition
                                               # file, e.g. .aws/task-definition.json
  CONTAINER_NAME: nginx          # set this to the name of the container in the
                                               # containerDefinitions section of your task definition

jobs:

  build:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.extract_branch.outputs.branch }}
    steps:
      - uses: actions/checkout@v2
      - name: Extract branch name
    shell: bash
    run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
    id: extract_branch

